#ifndef _SCRIPT_FUNCTIONS_H_
#define _SCRIPT_FUNCTIONS_H_

enum SCRIPT_FUNCTION_ID
{
	SF_IS_MUSIC_ENABLED,
	SF_IS_SOUND_EFFECTS_ENABLED,
	SF_GAMEPLAY_LOG,
	SF_TIME_ATTACK_ADD_LAP,
	SF_TIME_ATTACK_FINISH_LAP,
	SF_RESPAWN_PLAYER
};

#endif